# Meta Data for SEO

## Homepage
title = "Ubiq"
titleSeparator = ""
titleAddition = ""
description = "Ubiq is a Unity networking library for research, teaching and development, maintained by the Virtual Environments and Computer Graphics group at UCL. Ubiq is 100% free and open source."
banner = "images/banner.png"

## Open Graph
images = ["images/banner.png"]
ogLocale = "en_US"
domainTLD = "ubiq.online"
titleHome = "Ubiq"

## Twitter Cards
twitterSite = ""
twitterCreator = ""

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Doks"
schemaAuthor = "Nels Numan"
schemaAuthorTwitter = "https://twitter.com/nelsnuman"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/nsalminen/"
schemaAuthorGitHub = "https://github.com/nsalminen"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = ""
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "600"

# Footer
footer = ""

# Feed
copyRight = "Copyright (c) 2020-2022 UCL"


# Alert
alert = true
alertDismissable = true
alertText = "Instructions for the <strong>IEEE VR 2022 Tutorial can be found</strong> <a class=\"alert-link stretched-link\" href=\"/blog/doks-v0.4/\">here</a>!"

# Edit Page
docsRepo = "https://github.com/UCL-VR/ubiq-website"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  darkMode = true
  bootStrapJs = true
  highLight = true
  multilingualMode = false # Not yet functional
  docsVersioning = false # Not yet functional

[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = true
