# Meta Data for SEO

## Homepage
title = "Ubiq"
titleSeparator = ""
titleAddition = ""
description = "A Unity networking library for research, teaching and development, maintained by the Virtual Environments and Computer Graphics group at UCL. Ubiq is 100% free and open source."
banner = "images/banner.png"

## Open Graph
images = ["images/banner.png"]
ogLocale = "en_US"
domainTLD = "ubiq.online"
titleHome = "Ubiq"

## Twitter Cards
twitterSite = ""
twitterCreator = ""

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Ubiq"
schemaAuthor = "Nels Numan"
schemaLocale = "en-US"
schemaLogo = "images/logos/ubiq-logo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "images/banner.png"
schemaImageWidth = 1826
schemaImageHeight = 874
schemaGitHub = "https://github.com/UCL-VR/ubiq"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "600"

# Footer
footer = ""

# Feed
copyRight = "Copyright (c) 2020-2022 UCL"


# Alert
alert = false
alertDismissable = true
alertText = "Information on the <strong>Ubiq tutorial at IEEE VR 2022</strong> can be found <a class=\"alert-link stretched-link\" href=\"/blog/ubiq-tutorial-at-ieee-vr-2022/\">here</a>!"

# Edit Page
docsRepo = "https://github.com/UCL-VR/ubiq-website"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  darkMode = true
  bootStrapJs = true
  highLight = true
  multilingualMode = false # Not yet functional
  docsVersioning = false # Not yet functional

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
